version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - ./apps/api:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/inventory
      REDIS_URL: redis://redis:6379
    command: npm run dev
    user: root
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4000
    command: npm run dev
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
